### PR TITLE
Added ability to pass chunksize in arg parse

### PR DESCRIPTION
**Pull request by ghost**
- Check video was actually downloaded
- Add signal handling
- Changed default `chunk_size` to be 1MB

### CODE REVIEW

**Comment by luminousmen** [comment]
Why did you change chunk_size to be 1MB? Also, I think that when the user wants to stop downloading, it's necessary to delete the current not-fully-downloaded file

**Comment by ghost** [comment]
@luminousmen increasing the `chunk_size` allows for more data to be read/write at once, instead of many read/write(s) @ `8kb`.

Removing the file automatically would be pointless if the user stops the download. Doing the automatic delete would remove the ability to have auto resume downloading the file at the last byte received. Do you agree?

**Comment by luminousmen** [comment]
@voidpirate If you aren't very concerned about keeping memory usage down, go ahead and specify a large chunk size, such as 1 Mb. I think it's a good idea to increase `chunk_size`, but 1Mb is too much. And I'll keep chunk size option for any who want to increase it =)

**Comment by luminousmen** [comment]
@voidpirate I agree with you. The project was created for downloading a lot of small video files, it was my specific problem). So deleting one not-downloaded file means just keeping download folder clean. Thanks for your attention!

**Pull request merged**
